In [123]:
import pandas as pd
import os
import re

In [124]:
postings_path = "/Users/karmesh/Desktop/ResumeBoost-and-JobFit/datasets/postings.csv"

# Load the Job Postings CSV file into a Pandas DataFrame
postings_df = pd.read_csv(postings_path)

# Display the first few rows of the dataset to understand its structure
postings_df.head()

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,...,Requirements: \n\nWe are seeking a College or ...,1.713398e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,NaN,...,NaN,1.712858e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,83200.0,80521.0,8069.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,...,We are currently accepting resumes for FOH - A...,1.713278e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,...,This position requires a baseline understandin...,1.712896e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0,36059.0
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,80000.0,YEARLY,"Burlington, IA",NaN,3.0,NaN,...,NaN,1.713452e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,70000.0,52601.0,19057.0

In [125]:
postings_df.shape

(123849, 31)

In [126]:
postings_df.head()

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
0,921716,Corcoran Sawyer Smith,Marketing Coordinator,Job descriptionA leading real estate firm in N...,20.0,HOURLY,"Princeton, NJ",2774458.0,20.0,NaN,...,Requirements: \n\nWe are seeking a College or ...,1.713398e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0
1,1829192,NaN,Mental Health Therapist/Counselor,"At Aspen Therapy and Wellness , we are committ...",50.0,HOURLY,"Fort Collins, CO",NaN,1.0,NaN,...,NaN,1.712858e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,83200.0,80521.0,8069.0
2,10998357,The National Exemplar,Assitant Restaurant Manager,The National Exemplar is accepting application...,65000.0,YEARLY,"Cincinnati, OH",64896719.0,8.0,NaN,...,We are currently accepting resumes for FOH - A...,1.713278e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0
3,23221523,"Abrams Fensterman, LLP",Senior Elder Law / Trusts and Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,"New Hyde Park, NY",766262.0,16.0,NaN,...,This position requires a baseline understandin...,1.712896e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0,36059.0
4,35982263,NaN,Service Technician,Looking for HVAC service tech with experience ...,80000.0,YEARLY,"Burlington, IA",NaN,3.0,NaN,...,NaN,1.713452e+12,NaN,0,FULL_TIME,USD,BASE_SALARY,70000.0,52601.0,19057.0

In [127]:
postings_sample_df = postings_df.sample(1000)
postings_sample_df.shape

(1000, 31)

In [128]:
postings_sample_df.head()

,job_id,company_name,title,description,max_salary,pay_period,location,company_id,views,med_salary,...,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
86646,3904385264,The Learning Experience,Preschool Lead Teacher SIGN ON BONUS,Benefits:\n\n401(k)Competitive salaryDental in...,NaN,NaN,"Buffalo, New York, United States",485407.0,10.0,NaN,...,NaN,1.713392e+12,tle-careers.careerplug.com,0,FULL_TIME,NaN,NaN,NaN,NaN,NaN
23186,3889748602,Liberty Healthcare and Rehabilitation Services,PHYSICAL THERAPIST (PT) - ROXBORO HEALTHCARE &...,\nLiberty Cares\nWith Compassion\nAt Liberty H...,NaN,NaN,"Roxboro, NC",53345529.0,6.0,NaN,...,NaN,1.712667e+12,www.click2apply.net,0,FULL_TIME,NaN,NaN,NaN,27573.0,37145.0
5863,3885105160,"New Haven Youth and Family Services, Inc.",Counselor,Counselors\n\nOverview:\nCounselor positions a...,NaN,NaN,"Vista, CA",15558072.0,1.0,NaN,...,NaN,1.712393e+12,www.click2apply.net,0,FULL_TIME,NaN,NaN,NaN,92081.0,NaN
88236,3904393169,J.R. Simplot Company,Document Processing Technician HQ GS,"Location:\n\nBoise, ID, US, 83702-6924\n\nThe ...",NaN,NaN,"Boise, ID",23673.0,3.0,NaN,...,NaN,1.713395e+12,careers.simplot.com,0,FULL_TIME,NaN,NaN,NaN,83702.0,16001.0
18128,3888807290,"Volt Merchant Solutions, Inc",Technical Support Specialist,Job Summary:We are seeking a Technical Support...,NaN,NaN,Miami-Fort Lauderdale Area,84951391.0,30.0,NaN,...,NaN,1.712668e+12,NaN,0,FULL_TIME,NaN,NaN,NaN,NaN,NaN

In [ ]:
def preprocess_text(text):
    """Preprocess text by converting to lowercase, removing special characters, and handling NaN."""
    if pd.isnull(text):
        return ""
    text = text.lower()  # Convert to lowercase
    text = re.sub(r'[^\w\s]', '', text)  # Remove special characters
    return text.strip()

def combine_features(row):
    """Combine relevant features into a single string."""
    features = []
    for col in ['title', 'description', 'skills_desc']:
        if not pd.isnull(row[col]):
            features.append(f"{col.capitalize()}: {preprocess_text(row[col])}\n")
    return ' '.join(features)

# Apply preprocessing and feature combination
postings_sample_df['combined_features'] = postings_sample_df.apply(combine_features, axis=1)

# Display a sample of the combined data
postings_sample_df[['job_id', 'combined_features']].head()

           job_id                                  combined_features
86646  3904385264  Title: preschool lead teacher sign on bonus\n ...
23186  3889748602  Title: physical therapist pt  roxboro healthca...
5863   3885105160  Title: counselor\n Description: counselors\n\n...
88236  3904393169  Title: document processing technician hq gs\n ...
18128  3888807290  Title: technical support specialist\n Descript...

In [130]:
print(postings_sample_df.iloc[0]['combined_features'])

Title: preschool lead teacher sign on bonus
 Description: benefits

401kcompetitive salarydental insuranceemployee discountsflexible schedulefree uniformshealth insuranceopportunity for advancementpaid time offsigning bonustraining  developmentvision insurance

join the learning experience  upper west side and become part of our team of passionate preschool teachers we are looking for an experienced lead teacher to join us  qualified lead teachers receive a 500 sign on bonus

lead teachers at the learning experience are ambassadors of happiness creating opportunities every day that reflect our mission to make a difference in the lives of children their families and communities we believe that happy happens here  for our little learners and our team members this is why a supportive work environment money towards your health insurance company paid dental vision disability and life insurance and lots of other perks are so important to us

our passionate teachers use a growth mindset to develop young minds and inspire a love of learning

role responsibilities

lead coach and mentor less experienced teachers in your classroom model behaviors and provide feedbackresponsible for the overall classroom management leading a safe nurturing and engaging learning environmentserve as a role model using a growth mindset to develop young minds and inspire a love of learningimplement our proprietary leap curriculum working with infants toddlers andor preschool children in a way that is consistent with the unique needs of each childcreate a safe nurturing environment where children can play and learncommunicate regularly with parents sharing their childrens latest adventures and achievements through a variety of avenues including mobile apps and personal discussionssupport your centers success partnering with center staff and leadership to achieve goals around enrollment and engagementbuild relationships with families and coworkers and create a dynamic environment where play and learning happen seamlessly

qualifications

1 year of professional teaching experience preferred at least six months of professional teaching experience requiredbachelors degree in early childhood or associate degree or higher in ece or related degree preferred along with a study plan for obtaining early childcare certificationdemonstrated knowledge of developmentally appropriate practices dapcpr and first aide certification preferredmust meet state specific guidelines for the role

job type fulltime

salary 1800  2500 per hour

benefits

401khealth insurancepaid time off

schedule

monday to friday

education

bachelors preferred

licensecertification

child development associate certification preferrednys certification birth2nd preferred

compensation 2000  2500 per hour

the learning experience

at the learning experience we make early education joyful engaging and fun so children are happy to learn play and grow

our curriculum focuses on the six ages and stages of early childhood development and engages children in handson learning activities that encourage them to explore and solve problems at their own rate of development this forms a foundation for kids to learn play and grow under the care of our nurturing teachers and staff

at tle weve created a full cast of characters that become our little learners educators partners and friends through their preschool education journey each character has a unique personality and area of interest and brings learning to life by allowing children to explore the world through fun and imagination

tle cares benefits package  because we care about you

our center proudly offers tle cares a comprehensive benefits package for all team members all premiums for tle cares are fully paid by our centers owner with no cost to our employees

tle cares includes

 dental  vision insurance short  longterm disability insurance life insurance employee assistance program lifemart employee discount program

 this franchise is independently owned and operated by a franchisee your application will go directly to the franchisee and all hiring decisions will be made by the management of this franchisee all inquiries about employment at this franchisee should be made directly to the franchise location and not to the learning experience corporate

In [131]:
import pandas as pd
resume_path = '/Users/karmesh/Desktop/ResumeBoost-and-JobFit/datasets/Resume.csv'

resume_df = pd.read_csv(resume_path)

# Display the first few rows of the dataset to understand its structure
resume_df.head()

,ID,Resume_str,Resume_html,Category
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,"<div class=""fontsize fontface vmargins hmargin...",HR
1,22323967,"HR SPECIALIST, US HR OPERATIONS ...","<div class=""fontsize fontface vmargins hmargin...",HR
2,33176873,HR DIRECTOR Summary Over 2...,"<div class=""fontsize fontface vmargins hmargin...",HR
3,27018550,HR SPECIALIST Summary Dedica...,"<div class=""fontsize fontface vmargins hmargin...",HR
4,17812897,HR MANAGER Skill Highlights ...,"<div class=""fontsize fontface vmargins hmargin...",HR

In [145]:
def preprocess_resume_text(row):
    """Preprocess resume text by converting to lowercase, removing special characters, and handling NaN."""
    text = row.get('Resume_str', '') 
    if pd.isnull(text):
        return ""
    text = re.sub(r'[^\w\s,+./-]', '', text)  # Remove unwanted characters but retain important ones like +, , . / -
    text = re.sub(r'\s+', ' ', text)  # Remove extra whitespaces
    text = text.strip()  # Trim leading/trailing whitespace
    text = text.lower() # Normalize to lowercase
    
    return text

# Apply preprocessing
resume_df['preprocessed_resume'] = resume_df.apply(preprocess_resume_text, axis=1)

# Display the first 5 rows
resume_df[['ID', 'preprocessed_resume']].head()

         ID                                preprocessed_resume
0  16852973  hr administrator/marketing associate hr admini...
1  22323967  hr specialist, us hr operations summary versat...
2  33176873  hr director summary over 20 years experience i...
3  27018550  hr specialist summary dedicated, driven, and d...
4  17812897  hr manager skill highlights hr skills hr depar...

In [146]:
print(resume_df.iloc[0]['preprocessed_resume'])

hr administrator/marketing associate hr administrator summary dedicated customer service manager with 15+ years of experience in hospitality and customer service management. respected builder and leader of customer-focused teams strives to instill a shared, enthusiastic commitment to customer service. highlights focused on customer satisfaction team management marketing savvy conflict resolution techniques training and development skilled multi-tasker client relations specialist accomplishments missouri dot supervisor training certification certified by ihg in customer loyalty and marketing by segment hilton worldwide general manager training certification accomplished trainer for cross server hospitality systems such as hilton onq , micros opera pms , fidelio opera reservation system ors , holidex completed courses and seminars in customer service, sales strategies, inventory control, loss prevention, safety, time management, leadership and performance assessment. experience hr administrator/marketing associate hr administrator dec 2013 to current company name city , state helps to develop policies, directs and coordinates activities such as employment, compensation, labor relations, benefits, training, and employee services. prepares employee separation notices and related documentation keeps records of benefits plans participation such as insurance and pension plan, personnel transactions such as hires, promotions, transfers, performance reviews, and terminations, and employee statistics for government reporting. advises management in appropriate resolution of employee relations issues. administers benefits programs such as life, health, dental, insurance, pension plans, vacation, sick leave, leave of absence, and employee assistance. marketing associate designed and created marketing collateral for sales meetings, trade shows and company executives. managed the in-house advertising program consisting of print and media collateral pieces. assisted in the complete design and launch of the companys website in 2 months. created an official company page on facebook to facilitate interaction with customers. analyzed ratings and programming features of competitors to evaluate the effectiveness of marketing strategies. advanced medical claims analyst mar 2012 to dec 2013 company name city , state reviewed medical bills for the accuracy of the treatments, tests, and hospital stays prior to sanctioning the claims. trained to interpret the codes icd-9, cpt and terminology commonly used in medical billing to fully understand the paperwork that is submitted by healthcare providers. required to have organizational and analytical skills as well as computer skills, knowledge of medical terminology and procedures, statistics, billing standards, data analysis and laws regarding medical billing. assistant general manager jun 2010 to dec 2010 company name city , state performed duties including but not limited to, budgeting and financial management, accounting, human resources, payroll and purchasing. established and maintained close working relationships with all departments of the hotel to ensure maximum operation, productivity, morale and guest service. handled daily operations and reported directly to the corporate office. hired and trained staff on overall objectives and goals with an emphasis on high customer service. marketing and advertising, working on public relations with the media, government and local businesses and chamber of commerce. executive support / marketing assistant jul 2007 to jun 2010 company name city , state provided assistance to various department heads - executive, marketing, customer service, human resources. managed front-end operations to ensure friendly and efficient transactions. ensured the swift resolution of customer issues to preserve customer loyalty while complying with company policies. exemplified the second-to-none customer service delivery in all interactions with customers and potential clients. reservation front office manager jun 2004 to jul 2007 company name city , state owner/ partner dec 2001 to may 2004 company name city , state price integrity coordinator aug 1999 to dec 2001 company name city , state education n/a , business administration 1999 jefferson college city , state business administration marketing / advertising high school diploma , college prep. studies 1998 sainte genevieve senior high city , state awarded american shrubel leadership scholarship to jefferson college skills accounting, ads, advertising, analytical skills, benefits, billing, budgeting, clients, customer service, data analysis, delivery, documentation, employee relations, financial management, government relations, human resources, insurance, labor relations, layout, marketing, marketing collateral, medical billing, medical terminology, office, organizational, payroll, performance reviews, personnel, policies, posters, presentations, public relations, purchasing, reporting, statistics, website.

In [147]:
%pip install -U voyageai

Requirement already satisfied: voyageai in /opt/homebrew/lib/python3.11/site-packages (0.3.2)
Requirement already satisfied: aiohttp in /opt/homebrew/lib/python3.11/site-packages (from voyageai) (3.11.11)
Requirement already satisfied: aiolimiter in /opt/homebrew/lib/python3.11/site-packages (from voyageai) (1.2.1)
Requirement already satisfied: numpy in /opt/homebrew/lib/python3.11/site-packages (from voyageai) (1.26.4)
Requirement already satisfied: pillow in /opt/homebrew/lib/python3.11/site-packages (from voyageai) (11.1.0)
Requirement already satisfied: pydantic>=1.10.8 in /opt/homebrew/lib/python3.11/site-packages (from voyageai) (2.10.5)
Requirement already satisfied: requests in /opt/homebrew/lib/python3.11/site-packages (from voyageai) (2.32.3)
Requirement already satisfied: tenacity in /opt/homebrew/lib/python3.11/site-packages (from voyageai) (9.0.0)
Requirement already satisfied: tokenizers>=0.14.0 in /opt/homebrew/lib/python3.11/site-packages (from voyageai) (0.21.0)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/homebrew/lib/python3.11/site-packages (from pydantic>=1.10.8->voyageai) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /opt/homebrew/lib/python3.11/site-packages (from pydantic>=1.10.8->voyageai) (2.27.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /opt/homebrew/lib/python3.11/site-packages (from pydantic>=1.10.8->voyageai) (4.12.2)
Requirement already satisfied: huggingface-hub<1.0,>=0.16.4 in /opt/homebrew/lib/python3.11/site-packages (from tokenizers>=0.14.0->voyageai) (0.27.1)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /opt/homebrew/lib/python3.11/site-packages (from aiohttp->voyageai) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in /opt/homebrew/lib/python3.11/site-packages (from aiohttp->voyageai) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /opt/homebrew/lib/python3.11/site-packages (from aiohttp->voyageai) (24.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/homebrew/lib/python3.11/site-packages (from aiohttp->voyageai) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/homebrew/lib/python3.11/site-packages (from aiohttp->voyageai) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /opt/homebrew/lib/python3.11/site-packages (from aiohttp->voyageai) (0.2.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /opt/homebrew/lib/python3.11/site-packages (from aiohttp->voyageai) (1.18.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/homebrew/lib/python3.11/site-packages (from requests->voyageai) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /opt/homebrew/lib/python3.11/site-packages (from requests->voyageai) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/homebrew/lib/python3.11/site-packages (from requests->voyageai) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/homebrew/lib/python3.11/site-packages (from requests->voyageai) (2024.12.14)
Requirement already satisfied: filelock in /opt/homebrew/lib/python3.11/site-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers>=0.14.0->voyageai) (3.17.0)
Requirement already satisfied: fsspec>=2023.5.0 in /opt/homebrew/lib/python3.11/site-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers>=0.14.0->voyageai) (2024.12.0)
Requirement already satisfied: packaging>=20.9 in /opt/homebrew/lib/python3.11/site-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers>=0.14.0->voyageai) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /opt/homebrew/lib/python3.11/site-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers>=0.14.0->voyageai) (6.0.2)
Requirement already satisfied: tqdm>=4.42.1 in /opt/homebrew/lib/python3.11/site-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers>=0.14.0->voyageai) (4.67.1)
Note: you may need to restart the kernel to use updated packages.

In [148]:
import config
import voyageai

In [149]:
import voyageai
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from voyage_config import VOYAGE_API_KEY

# Initialize the Voyage API client
vo = voyageai.Client(api_key=VOYAGE_API_KEY)
embedding_model = "voyage-3-lite"

# Function to generate embeddings in batches
def generate_embeddings(texts, batch_size=128):
    all_embeddings = []
    for i in range(0, len(texts), batch_size):
        batch = texts[i : i + batch_size]
        try:
            result = vo.embed(batch, model=embedding_model, input_type="document")
            all_embeddings.extend(result.embeddings)
        except Exception as e:
            print(f"Error generating embeddings: {e}")
            return None
    return all_embeddings

# Function to find similar jobs
def find_similar_jobs(resume_embedding, postings_df, top_n=5):
    """Finds the most similar job postings to a given resume embedding."""
    job_embeddings = np.array(postings_df['embeddings'].tolist())
    similarities = cosine_similarity([resume_embedding], job_embeddings)[0]
    top_indices = similarities.argsort()[-top_n:][::-1]
    return top_indices

# Main execution
if __name__ == "__main__":
    # Load YOUR resume dataset (replace with your actual path)
    resume_path = "/Users/karmesh/Desktop/ResumeBoost-and-JobFit/datasets/Resume.csv"  # Update this path
    resume_df = pd.read_csv(resume_path)
    
    # Load YOUR job postings dataset (already loaded as postings_df in previous steps)
    postings_path = "/Users/karmesh/Desktop/ResumeBoost-and-JobFit/datasets/postings.csv"
    postings_df = pd.read_csv(postings_path)

    # Preprocess job postings (combine title and description)
    postings_df['combined_features'] = postings_df['title'] + " " + postings_df['description']
    postings_df['combined_features'] = postings_df['combined_features'].fillna('')

    # Generate embeddings for job postings
    postings_df['embeddings'] = generate_embeddings(postings_df['combined_features'].tolist())

    # Generate embedding for a specific resume (e.g., the first resume in your dataset)
    resume_text = resume_df.iloc[0]['preprocessed_resume']
    resume_embedding = generate_embeddings([resume_text])[0]

    # Find top 5 similar jobs
    similar_job_indices = find_similar_jobs(resume_embedding, postings_df)

    # Print results
    print("Top job matches for resume:")
    print("-" * 50)
    print(f"Resume ID: {resume_df.iloc[0]['ID']}")
    print(f"Resume Content: {resume_df.iloc[0]['preprocessed_resume']}")
    print("-" * 50)

    for i, job_index in enumerate(similar_job_indices):
        job_posting = postings_df.iloc[job_index]
        print(f"Match {i+1}:")
        print(f"Job ID: {job_posting['job_id']}")
        print(f"Title: {job_posting['title']}")
        print(f"Similarity Score: {cosine_similarity([resume_embedding], [job_posting['embeddings']])[0][0]:.4f}")
        print(f"Description: {job_posting['description'][:200]}...")  # Truncate for readability
        print("-" * 50)

Error generating embeddings: You have not yet added your payment method in the billing page and will have reduced rate limits of 3 RPM and 10K TPM.  Please add your payment method in the billing page (https://dash.voyageai.com/billing/payment-methods) to unlock our standard rate limits (https://docs.voyageai.com/docs/rate-limits).  Even with payment methods entered, the free tokens (200M tokens for Voyage series 3) will still apply. See our pricing docs (https://docs.voyageai.com/docs/pricing) for the free tokens for your model.

KeyError: 'preprocessed_resume'

In [137]:
resume_df.head()

,preprocessed_resume,Resume_str
0,Experienced software engineer with expertise i...,Experienced software engineer with expertise i...

In [150]:
%pip install sentence-transformers scikit-learn

Collecting sentence-transformers
  Using cached sentence_transformers-3.4.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: scikit-learn in /opt/homebrew/lib/python3.11/site-packages (1.5.2)
Collecting transformers<5.0.0,>=4.41.0 (from sentence-transformers)
  Using cached transformers-4.48.1-py3-none-any.whl.metadata (44 kB)
Requirement already satisfied: tqdm in /opt/homebrew/lib/python3.11/site-packages (from sentence-transformers) (4.67.1)
Collecting torch>=1.11.0 (from sentence-transformers)
  Downloading torch-2.5.1-cp311-none-macosx_11_0_arm64.whl.metadata (28 kB)
Requirement already satisfied: scipy in /opt/homebrew/lib/python3.11/site-packages (from sentence-transformers) (1.10.1)
Requirement already satisfied: huggingface-hub>=0.20.0 in /opt/homebrew/lib/python3.11/site-packages (from sentence-transformers) (0.27.1)
Requirement already satisfied: Pillow in /opt/homebrew/lib/python3.11/site-packages (from sentence-transformers) (11.1.0)
Requirement already satisfied: numpy>=1.19.5 in /opt/homebrew/lib/python3.11/site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: joblib>=1.2.0 in /opt/homebrew/lib/python3.11/site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/homebrew/lib/python3.11/site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: filelock in /opt/homebrew/lib/python3.11/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.17.0)
Requirement already satisfied: fsspec>=2023.5.0 in /opt/homebrew/lib/python3.11/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2024.12.0)
Requirement already satisfied: packaging>=20.9 in /opt/homebrew/lib/python3.11/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /opt/homebrew/lib/python3.11/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.2)
Requirement already satisfied: requests in /opt/homebrew/lib/python3.11/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2.32.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /opt/homebrew/lib/python3.11/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (4.12.2)
Requirement already satisfied: networkx in /opt/homebrew/lib/python3.11/site-packages (from torch>=1.11.0->sentence-transformers) (3.2.1)
Requirement already satisfied: jinja2 in /opt/homebrew/lib/python3.11/site-packages (from torch>=1.11.0->sentence-transformers) (3.1.5)
Collecting sympy==1.13.1 (from torch>=1.11.0->sentence-transformers)
  Downloading sympy-1.13.1-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /opt/homebrew/lib/python3.11/site-packages (from sympy==1.13.1->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: regex!=2019.12.17 in /opt/homebrew/lib/python3.11/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2024.11.6)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /opt/homebrew/lib/python3.11/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.21.0)
Collecting safetensors>=0.4.1 (from transformers<5.0.0,>=4.41.0->sentence-transformers)
  Downloading safetensors-0.5.2-cp38-abi3-macosx_11_0_arm64.whl.metadata (3.8 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/homebrew/lib/python3.11/site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/homebrew/lib/python3.11/site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /opt/homebrew/lib/python3.11/site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/homebrew/lib/python3.11/site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/homebrew/lib/python3.11/site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2024.12.14)
Downloading sentence_transformers-3.4.0-py3-none-any.whl (275 kB)
Downloading torch-2.5.1-cp311-none-macosx_11_0_arm64.whl (63.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.9/63.9 MB 420.4 kB/s eta 0:00:0000:0100:05
Downloading sympy-1.13.1-py3-none-any.whl (6.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 410.1 kB/s eta 0:00:00a 0:00:02
Downloading transformers-4.48.1-py3-none-any.whl (9.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.7/9.7 MB 440.9 kB/s eta 0:00:0000:0100:02
Downloading safetensors-0.5.2-cp38-abi3-macosx_11_0_arm64.whl (408 kB)
Installing collected packages: sympy, safetensors, torch, transformers, sentence-transformers
  Attempting uninstall: sympy
    Found existing installation: sympy 1.12
    Uninstalling sympy-1.12:
      Successfully uninstalled sympy-1.12
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
qiskit-terra 0.45.0 requires symengine<0.10,>=0.9; platform_machine == "x86_64" or platform_machine == "aarch64" or platform_machine == "ppc64le" or platform_machine == "amd64" or platform_machine == "arm64", but you have symengine 0.11.0 which is incompatible.
Successfully installed safetensors-0.5.2 sentence-transformers-3.4.0 sympy-1.13.1 torch-2.5.1 transformers-4.48.1
Note: you may need to restart the kernel to use updated packages.

In [ ]:

import pandas as pd
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

# ----------------------
# 1. Load Model
# ----------------------
model = SentenceTransformer('all-MiniLM-L6-v2')  # Lightweight model

# ----------------------
# 2. Generate Embeddings Locally
# ----------------------
def generate_embeddings(texts):
    return model.encode(texts, convert_to_tensor=False)

# ----------------------
# 3. Similarity Search (Modified)
# ----------------------
def find_job_matches(resume_id, top_n=5):
    # Load data (same as before)
    postings_df, resume_df = load_and_preprocess_data()
    
    # Generate embeddings
    job_embeddings = generate_embeddings(postings_df['combined_features'].tolist())
    resume_embedding = generate_embeddings([resume_df.loc[resume_id, 'processed']])[0]
    
    # Calculate similarities
    similarities = cosine_similarity([resume_embedding], job_embeddings)[0]
    top_indices = similarities.argsort()[-top_n:][::-1]
    
    # Return results (same as before)
    return format_results(top_indices, postings_df, similarities)